Gourmet Command
wrightedu/CSE-Discord-Bot pull request #140
Opened 2022-07-25 18:21 UTC by ReginPotter

# Description

Added a command that will recommend restaurants to the user. The user can also add and remove restaurants from the list. The choices are currently vegan and normal.

## Issues

Closes #88

## Type of change

Select one or more of the following:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (describe below)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. List any edge cases you tested.
If you come up with any edge cases you didn't test while writing this PR, cancel the PR and test again.

- [ ] Test A
       - `-feedme`
       - try out any button
- [ ] Test B
       - `-feedme`
       - try out meat until there are no more restaurants
       - `-feedme`
       - try out meat once more

# Checklist:

- [X] All local commits have been pushed to remote
- [X] All changes on the base branch have been merged into this branch, either by rebase or merge
- [X] My code is [PEP-8](https://pep8.org/) compliant (excluding maximum line length, keep that to 100ish characters)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added [Google Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for all new functions/methods
- [X] I have made corresponding changes to the documentation

2022-07-27 15:04 UTC, mbozada commented on Cogs/Gourmet.py
> +        self.normal_restaurant = []
I think a cleaner implementation would be to find a way to initialize these lists when the Cog is loaded.

Talk with Anmol about the work he's doing with faqbot. We read the file in the setup() function, and then pass some additional parameters to the Cog Initialization.

Once you have the file read in, feedme can work by making copies of the attributes:
`restaurants = self.normal_restaurants`

2022-07-27 15:19 UTC, mbozada requested changes
This is a great first step for the gourmet command. Good job Regin!

The big thing I want you to work on is reading in the file during setup and working off of a copy for the list.

A small thing that would be nice is if you could change the way the restaurants are posted. Right now the new messages with recommendations eventually push the button off the screen.
![image](https://user-images.githubusercontent.com/52613673/181285086-f5999719-3e89-4dba-b29d-b5e353e08ba2.png)

Maybe view has a line for text output? Every time a button is pushed the line gets edited with relevant output.

2022-07-27 18:34 UTC, mbozada approved these changes
This is a good start!

If you could go ahead and update issue #88 or create a new issue with our desired future features, then I think you're done for now!

2022-08-09 20:28 UTC, L30N1DAS commented
Good work! The function does it's job very well. It doesn't seem added restaurants persist upon shutdown of the bot though and more functionality could definitely be added later. Can be pulled into master now however.

2022-08-09 20:28 UTC, merged