Dropdown
wrightedu/CSE-Discord-Bot pull request #218
Opened 2023-03-29 16:18 UTC by ReginPotter

# Description

I added an autofill feature to all commands in the CogManagement cog.

## Issues

Closes #211 

## Type of change

Select one or more of the following:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (describe below)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. List any edge cases you tested.
If you come up with any edge cases you didn't test while writing this PR, cancel the PR and test again.

- [ ] Test A
        - Type in `/load` without pressing enter
        - Once the parameter shows up it should show all potential choices for the parameter 
- [ ] Test B
        - Type in `/unload` without pressing enter
        - Once the parameter shows up it should show all potential choices for the parameter  
- [ ] Test C 
        - Type in `/reload` without pressing enter
        - Once the parameter shows up it should show all potential choices for the parameter  

# Checklist:

- [X] All local commits have been pushed to remote
- [X] All changes on the base branch have been merged into this branch, either by rebase or merge
- [X] My code is [PEP-8](https://pep8.org/) compliant (excluding maximum line length, keep that to 100ish characters)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added [Google Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for all new functions/methods
- [X] I have made corresponding changes to the documentation

2023-03-29 18:43 UTC, NicoleP23 approved these changes
Needed to give ``-sync`` a second to see it show up, but tested all three tests once it showed up and they all worked for me :+1:

2023-03-31 20:44 UTC, L30N1DAS requested changes
I think the Google docstrings should be updated to reflect the implemented autocomplete functionality.

I will review the PR more thoroughly after this change has been implemented (or I can be convinced that it is not necessary) to ensure that no additional undesired changes are implemented after my review.

2023-04-03 17:32 UTC, ReginPotter commented
> I think the Google docstrings should be updated to reflect the implemented autocomplete functionality.
> 
> I will review the PR more thoroughly after this change has been implemented (or I can be convinced that it is not necessary) to ensure that no additional undesired changes are implemented after my review.

I have edited the docstrings to show the new functionality added. Please review again

2023-04-03 19:18 UTC, NicoleP23 requested changes

2023-04-03 19:18 UTC, NicoleP23 commented on Cogs/CogManagement.py
>          file = abspath('Cogs/' + cog_name + '.py')
Re-add this comment and line 35's comment to keep consistent comments along the functions please.

2023-04-03 20:51 UTC, L30N1DAS approved these changes
Looks good. Ran into the following error twice but am unable to replicate it: 
![image](https://user-images.githubusercontent.com/77419369/229624639-939d404f-08c4-4a6f-b558-1c6982a3b07d.png)

2023-04-10 19:52 UTC, Kokuko3 reviewed
I like it, clip it and ship it.

2023-05-08 19:36 UTC, merged