Rr dc
wrightedu/CSE-Discord-Bot pull request #54
Opened 2021-06-23 21:49 UTC by CodingPenguin1

Resolves #39 
Resolves #43 
Resolves #41 

EVERYTHING WITH ROLE MENUS WORKS

Added REQUIREMENTS.txt to list all requirements

-buildserver, -destroyserver, and -rolemenu are all cleaner. Built off CSV instead of JSON:
```
text,emoji,role/link,long_name,create_channels
CEG 3310,,CEG3310,some ceg class idk,"#ceg3310,0#Student Voice,2#TA Voice"
CEG 4324,,CEG4324,some other ceg class idk,"#ceg4324,0#Student Voice,2#TA Voice"
WSU Esports!,,https://discord.gg/smmV38d,,
CS 1000,,CS1000,demo cs class,"#cs1000,0#Student Voice,2#TA Voice"
EE 9999,,EE9999,demo ee class,"#ee9999,0#Student Voice,2#TA Voice"```

Can specify channels per category, if starts with `#`, text channel. If starts with number before `#`, that's the max number of people allowed in the VC. 0 for infinite.

-buildserver and -rolemenu accept new csv as attachment. If passed, local copy replaced. Saved per-server.

Moved to discord-components instead of reactions for getting roles. Will need to be rewritten when discord-py 2.0 comes out, but that won't be for a while.

Role menus now function through a full bot restart or a cog restart. Cached in `role_menus.json`, which is updated every time a new role menu is made.

Lots more confirms for stuff

-rolemenu now automatically determines what channel to use first 2-3 characters of role column to determine which `*-class-selection` channel to use. If unsure, asks for user input.

Probably some other features, but I've forgotten them. Buttons are nice. Code is slightly bigger than old version I think, but it's _significantly_ more readable. Less caching in objects, and no more dicts of dicts of lists of dicts of dicts or whatever I was doing before

2021-06-24 02:41 UTC, tux2603 requested changes

2021-06-24 02:41 UTC, tux2603 commented on Cogs/ServerManagement.py
> +                message = await channel.send('‍', components=menu)  # 0 width joiner in here to send empty message
Maybe use the escape code for the ZWJ?

2021-06-24 02:45 UTC, CodingPenguin1 commented on Cogs/ServerManagement.py
> +                permissions = discord.Permissions(read_messages=True, send_messages=True, embed_links=True, attach_files=True, read_message_history=True, add_reactions=True, connect=True, speak=True,
> 
> 
> This should get modified to fix issue #46

I'll move this to a separate PR

2021-06-24 13:26 UTC, CodingPenguin1 commented on Cogs/ServerManagement.py
> +                message = await channel.send('‍', components=menu)  # 0 width joiner in here to send empty message
Resolved by 1d93ff4

2021-06-24 14:32 UTC, CodingPenguin1 commented
change ilocs in destroyserver() to df['header']

2021-06-25 15:29 UTC, CodingPenguin1 commented
Resolved #46

2021-06-25 15:29 UTC, CodingPenguin1 commented on Cogs/ServerManagement.py
> +                permissions = discord.Permissions(read_messages=True, send_messages=True, embed_links=True, attach_files=True, read_message_history=True, add_reactions=True, connect=True, speak=True,
Jk now resolved #46

2021-06-25 15:41 UTC, tux2603 requested changes

2021-06-25 15:41 UTC, tux2603 commented on Cogs/ServerManagement.py
> +                    buttons.append(Button(style=ButtonStyle.gray, label=text, emoji=await get_emoji_named(ctx.guild, emoji)))
Maybe add some sort of check to see if the server has an emoji with the name, and if not fall back to the default emojis?

2021-06-25 17:48 UTC, tux2603 approved these changes

2021-06-25 17:48 UTC, merged